version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:d5:77:06:8d:2a:a9:17:42:4c:f2:a3:c8:e7:c0:4f"

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn chromatic test --app-code=oqoauq7zoea --exit-zero-on-changes
      - run: |
          if [ $CIRCLE_BRANCH = "master" ]
          then
            yarn release
          fi
